Timothy (fancy to do app)
agile-fox-kg-01/FancyTodo-Server pull request #8
Opened 2020-07-07 11:09 UTC by Timothychenn

1. Add middleware for handling error
2. Rename due_date column to dueDate
3. Add env file to save credential data
4. Add 3rd party API: bored (https://www.boredapi.com/)
 - when creating a new to do, if title = bored, will generate a random activity
5. Update API Documentation

2020-07-07 14:13 UTC, Timothychenn commented
add 3rd party API: mailgun (https://www.mailgun.com/)

ENV data:
CONFIG_USERNAME=postgres
CONFIG_PASSWORD=postgres
CONFIG_HOST='127.0.0.1'
JWT_SECRET=rahasia
MAILGUN_API_KEY='4000d7d5a06aedaf5290f8a2e1ca98e4-87c34c41-2a50452b'
MAILGUN_DOMAIN='sandbox710b35b55b724cad928833d39ac6013d.mailgun.org'

2020-07-08 13:43 UTC, dmtrxw requested changes

2020-07-08 13:43 UTC, dmtrxw commented on .env-template
> +CONFIG_USERNAME=
Ini mungkin namain `DB_USERNAME` aja ya. Soalnya kalo lu tulis macem begini bikin orang bingung ini username buat apaan

2020-07-08 13:43 UTC, dmtrxw commented on controllers/todo-controller.js
> +                res.status(200).json(result[1])
`result[1]` bikinin variable aja. Bisa lu pake destructuring biar orang lain tau kenapa pake index 1.

```
const [status, todo] = result;
```

2020-07-08 13:43 UTC, dmtrxw commented on controllers/todo-controller.js
> +        let title = req.body.title;
Pake destructuring lebih ok.

```
const { title, description, status, dueDate } = req.body;
```

2020-07-08 13:43 UTC, dmtrxw commented on middleware/auth.js
> +                res.status(401).json(
Throw error sekalian biar langsung di-handle sama middleware lu.

2020-07-08 13:43 UTC, dmtrxw commented on middleware/auth.js
> +                res.status(401).json(
Berlaku juga buat error lain yang masih lu handle di middleware. Middlewares ini bisa akses error handler karena punya `next`

2020-07-08 13:43 UTC, dmtrxw commented on package.json
> +    "nodemon": "^2.0.4",
`nodemon` simpen sebagai `devDependencies` aja (`npm install --save-dev nodemon`). Karena kita ga butuh `nodemon` di production.

2020-07-08 13:43 UTC, closed without merging